### ISSUE TITLE
我想监听mqtt的多个topic，把它们发送到kafka，这是否是可以实现的？

### ISSUE THREAD

**Issue by Knightwood** [jostar-y/emqx_plugin_kafka#4]
可以在配置文件中 filter多个topic吗？像这样
 // required
  hooks = [
    {
      endpoint = message.publish
      filter = "test/#" 
      kafka_topic = emqx_test
    },
{
      endpoint = message.publish
      filter = "abc/#" 
      kafka_topic = emqx_test2
    }
  ]

**Comment by jostar-y** [comment]
可以的，请参考示例  priv/example/example_1.hocon
