### ISSUE TITLE
Optimization suggestions

### ISSUE THREAD

**Issue by thousmile** [jostar-y/emqx_plugin_kafka#6]
It is recommended to put parameters such as emqx Id, Topic, Node, From, Qos, Timestamp, etc. in the Kafka message header. Payload is stored in the Kafka message body. payload supports any binary data

example: 
![image](https://github.com/user-attachments/assets/73ed9c0d-3660-4e5a-8be8-2dabe081719d)

**Comment by jostar-y** [comment]
ok, I will give it a try

**Comment by thousmile** [comment]
> ok, I will give it a try

Thanks, looking forward to the next version!
